import Foundation

class RecyclabilityData {
    @Published public var data = [
        "background": [false, nil],
        "tench, Tinca tinca": [false, nil],
        "goldfish, Carassius auratus": [false, nil],
        "great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias": [false, nil],
        "tiger shark, Galeocerdo cuvieri": [false, nil],
        "hammerhead, hammerhead shark": [false, nil],
        "electric ray, crampfish, numbfish, torpedo": [false, nil],
        "stingray": [false, nil],
        "cock": [false, nil],
        "hen": [false, nil],
        "ostrich, Struthio camelus": [false, nil],
        "brambling, Fringilla montifringilla": [false, nil],
        "goldfinch, Carduelis carduelis": [false, nil],
        "house finch, linnet, Carpodacus mexicanus": [false, nil],
        "junco, snowbird": [false, nil],
        "indigo bunting, indigo finch, indigo bird, Passerina cyanea": [false, nil],
        "robin, American robin, Turdus migratorius": [false, nil],
        "bulbul": [false, nil],
        "jay": [false, nil],
        "magpie": [false, nil],
        "chickadee": [false, nil],
        "water ouzel, dipper": [false, nil],
        "kite": [false, nil],
        "bald eagle, American eagle, Haliaeetus leucocephalus": [false, nil],
        "vulture": [false, nil],
        "great grey owl, great gray owl, Strix nebulosa": [false, nil],
        "European fire salamander, Salamandra salamandra": [false, nil],
        "common newt, Triturus vulgaris": [false, nil],
        "eft": [false, nil],
        "spotted salamander, Ambystoma maculatum": [false, nil],
        "axolotl, mud puppy, Ambystoma mexicanum": [false, nil],
        "bullfrog, Rana catesbeiana": [false, nil],
        "tree frog, tree-frog": [false, nil],
        "tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui": [false, nil],
        "loggerhead, loggerhead turtle, Caretta caretta": [false, nil],
        "leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea": [false, nil],
        "mud turtle": [false, nil],
        "terrapin": [false, nil],
        "box turtle, box tortoise": [false, nil],
        "banded gecko": [false, nil],
        "common iguana, iguana, Iguana iguana": [false, nil],
        "American chameleon, anole, Anolis carolinensis": [false, nil],
        "whiptail, whiptail lizard": [false, nil],
        "agama": [false, nil],
        "frilled lizard, Chlamydosaurus kingi": [false, nil],
        "alligator lizard": [false, nil],
        "Gila monster, Heloderma suspectum": [false, nil],
        "green lizard, Lacerta viridis": [false, nil],
        "African chameleon, Chamaeleo chamaeleon": [false, nil],
        "Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis": [false, nil],
        "African crocodile, Nile crocodile, Crocodylus niloticus": [false, nil],
        "American alligator, Alligator mississipiensis": [false, nil],
        "triceratops": [false, nil],
        "thunder snake, worm snake, Carphophis amoenus": [false, nil],
        "ringneck snake, ring-necked snake, ring snake": [false, nil],
        "hognose snake, puff adder, sand viper": [false, nil],
        "green snake, grass snake": [false, nil],
        "king snake, kingsnake": [false, nil],
        "garter snake, grass snake": [false, nil],
        "water snake": [false, nil],
        "vine snake": [false, nil],
        "night snake, Hypsiglena torquata": [false, nil],
        "boa constrictor, Constrictor constrictor": [false, nil],
        "rock python, rock snake, Python sebae": [false, nil],
        "Indian cobra, Naja naja": [false, nil],
        "green mamba": [false, nil],
        "sea snake": [false, nil],
        "horned viper, cerastes, sand viper, horned asp, Cerastes cornutus": [false, nil],
        "diamondback, diamondback rattlesnake, Crotalus adamanteus": [false, nil],
        "sidewinder, horned rattlesnake, Crotalus cerastes": [false, nil],
        "trilobite": [false, nil],
        "harvestman, daddy longlegs, Phalangium opilio": [false, nil],
        "scorpion": [false, nil],
        "black and gold garden spider, Argiope aurantia": [false, nil],
        "barn spider, Araneus cavaticus": [false, nil],
        "garden spider, Aranea diademata": [false, nil],
        "black widow, Latrodectus mactans": [false, nil],
        "tarantula": [false, nil],
        "wolf spider, hunting spider": [false, nil],
        "tick": [false, nil],
        "centipede": [false, nil],
        "black grouse": [false, nil],
        "ptarmigan": [false, nil],
        "ruffed grouse, partridge, Bonasa umbellus": [false, nil],
        "prairie chicken, prairie grouse, prairie fowl": [false, nil],
        "peacock": [false, nil],
        "quail": [false, nil],
        "partridge": [false, nil],
        "African grey, African gray, Psittacus erithacus": [false, nil],
        "macaw": [false, nil],
        "sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita": [false, nil],
        "lorikeet": [false, nil],
        "coucal": [false, nil],
        "bee eater": [false, nil],
        "hornbill": [false, nil],
        "hummingbird": [false, nil],
        "jacamar": [false, nil],
        "toucan": [false, nil],
        "drake": [false, nil],
        "red-breasted merganser, Mergus serrator": [false, nil],
        "goose": [false, nil],
        "black swan, Cygnus atratus": [false, nil],
        "tusker": [false, nil],
        "echidna, spiny anteater, anteater": [false, nil],
        "platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus": [false, nil],
        "wallaby, brush kangaroo": [false, nil],
        "koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus": [false, nil],
        "wombat": [false, nil],
        "jellyfish": [false, nil],
        "sea anemone, anemone": [false, nil],
        "brain coral": [false, nil],
        "flatworm, platyhelminth": [false, nil],
        "nematode, nematode worm, roundworm": [false, nil],
        "conch": [false, nil],
        "snail": [false, nil],
        "slug": [false, nil],
        "sea slug, nudibranch": [false, nil],
        "chiton, coat-of-mail shell, sea cradle, polyplacophore": [false, nil],
        "chambered nautilus, pearly nautilus, nautilus": [false, nil],
        "Dungeness crab, Cancer magister": [false, nil],
        "rock crab, Cancer irroratus": [false, nil],
        "fiddler crab": [false, nil],
        "king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica": [false, nil],
        "American lobster, Northern lobster, Maine lobster, Homarus americanus": [false, nil],
        "spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish": [false, nil],
        "crayfish, crawfish, crawdad, crawdaddy": [false, nil],
        "hermit crab": [false, nil],
        "isopod": [false, nil],
        "white stork, Ciconia ciconia": [false, nil],
        "black stork, Ciconia nigra": [false, nil],
        "spoonbill": [false, nil],
        "flamingo": [false, nil],
        "little blue heron, Egretta caerulea": [false, nil],
        "American egret, great white heron, Egretta albus": [false, nil],
        "bittern": [false, nil],
        "limpkin, Aramus pictus": [false, nil],
        "European gallinule, Porphyrio porphyrio": [false, nil],
        "American coot, marsh hen, mud hen, water hen, Fulica americana": [false, nil],
        "bustard": [false, nil],
        "ruddy turnstone, Arenaria interpres": [false, nil],
        "red-backed sandpiper, dunlin, Erolia alpina": [false, nil],
        "redshank, Tringa totanus": [false, nil],
        "dowitcher": [false, nil],
        "oystercatcher, oyster catcher": [false, nil],
        "pelican": [false, nil],
        "king penguin, Aptenodytes patagonica": [false, nil],
        "albatross, mollymawk": [false, nil],
        "grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus": [false, nil],
        "killer whale, killer, orca, grampus, sea wolf, Orcinus orca": [false, nil],
        "dugong, Dugong dugon": [false, nil],
        "sea lion": [false, nil],
        "Chihuahua": [false, nil],
        "Japanese spaniel": [false, nil],
        "Maltese dog, Maltese terrier, Maltese": [false, nil],
        "Pekinese, Pekingese, Peke": [false, nil],
        "Shih-Tzu": [false, nil],
        "Blenheim spaniel": [false, nil],
        "papillon": [false, nil],
        "toy terrier": [false, nil],
        "Rhodesian ridgeback": [false, nil],
        "Afghan hound, Afghan": [false, nil],
        "basset, basset hound": [false, nil],
        "beagle": [false, nil],
        "bloodhound, sleuthhound": [false, nil],
        "bluetick": [false, nil],
        "black-and-tan coonhound": [false, nil],
        "Walker hound, Walker foxhound": [false, nil],
        "English foxhound": [false, nil],
        "redbone": [false, nil],
        "borzoi, Russian wolfhound": [false, nil],
        "Irish wolfhound": [false, nil],
        "Italian greyhound": [false, nil],
        "whippet": [false, nil],
        "Ibizan hound, Ibizan Podenco": [false, nil],
        "Norwegian elkhound, elkhound": [false, nil],
        "otterhound, otter hound": [false, nil],
        "Saluki, gazelle hound": [false, nil],
        "Scottish deerhound, deerhound": [false, nil],
        "Weimaraner": [false, nil],
        "Staffordshire bullterrier, Staffordshire bull terrier": [false, nil],
        "American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier": [false, nil],
        "Bedlington terrier": [false, nil],
        "Border terrier": [false, nil],
        "Kerry blue terrier": [false, nil],
        "Irish terrier": [false, nil],
        "Norfolk terrier": [false, nil],
        "Norwich terrier": [false, nil],
        "Yorkshire terrier": [false, nil],
        "wire-haired fox terrier": [false, nil],
        "Lakeland terrier": [false, nil],
        "Sealyham terrier, Sealyham": [false, nil],
        "Airedale, Airedale terrier": [false, nil],
        "cairn, cairn terrier": [false, nil],
        "Australian terrier": [false, nil],
        "Dandie Dinmont, Dandie Dinmont terrier": [false, nil],
        "Boston bull, Boston terrier": [false, nil],
        "miniature schnauzer": [false, nil],
        "giant schnauzer": [false, nil],
        "standard schnauzer": [false, nil],
        "Scotch terrier, Scottish terrier, Scottie": [false, nil],
        "Tibetan terrier, chrysanthemum dog": [false, nil],
        "silky terrier, Sydney silky": [false, nil],
        "soft-coated wheaten terrier": [false, nil],
        "West Highland white terrier": [false, nil],
        "Lhasa, Lhasa apso": [false, nil],
        "flat-coated retriever": [false, nil],
        "curly-coated retriever": [false, nil],
        "golden retriever": [false, nil],
        "Labrador retriever": [false, nil],
        "Chesapeake Bay retriever": [false, nil],
        "German short-haired pointer": [false, nil],
        "vizsla, Hungarian pointer": [false, nil],
        "English setter": [false, nil],
        "Irish setter, red setter": [false, nil],
        "Gordon setter": [false, nil],
        "Brittany spaniel": [false, nil],
        "clumber, clumber spaniel": [false, nil],
        "English springer, English springer spaniel": [false, nil],
        "Welsh springer spaniel": [false, nil],
        "cocker spaniel, English cocker spaniel, cocker": [false, nil],
        "Sussex spaniel": [false, nil],
        "Irish water spaniel": [false, nil],
        "kuvasz": [false, nil],
        "schipperke": [false, nil],
        "groenendael": [false, nil],
        "malinois": [false, nil],
        "briard": [false, nil],
        "kelpie": [false, nil],
        "komondor": [false, nil],
        "Old English sheepdog, bobtail": [false, nil],
        "Shetland sheepdog, Shetland sheep dog, Shetland": [false, nil],
        "collie": [false, nil],
        "Border collie": [false, nil],
        "Bouvier des Flandres, Bouviers des Flandres": [false, nil],
        "Rottweiler": [false, nil],
        "German shepherd, German shepherd dog, German police dog, alsatian": [false, nil],
        "Doberman, Doberman pinscher": [false, nil],
        "miniature pinscher": [false, nil],
        "Greater Swiss Mountain dog": [false, nil],
        "Bernese mountain dog": [false, nil],
        "Appenzeller": [false, nil],
        "EntleBucher": [false, nil],
        "boxer": [false, nil],
        "bull mastiff": [false, nil],
        "Tibetan mastiff": [false, nil],
        "French bulldog": [false, nil],
        "Great Dane": [false, nil],
        "Saint Bernard, St Bernard": [false, nil],
        "Eskimo dog, husky": [false, nil],
        "malamute, malemute, Alaskan malamute": [false, nil],
        "Siberian husky": [false, nil],
        "dalmatian, coach dog, carriage dog": [false, nil],
        "affenpinscher, monkey pinscher, monkey dog": [false, nil],
        "basenji": [false, nil],
        "pug, pug-dog": [false, nil],
        "Leonberg": [false, nil],
        "Newfoundland, Newfoundland dog": [false, nil],
        "Great Pyrenees": [false, nil],
        "Samoyed, Samoyede": [false, nil],
        "Pomeranian": [false, nil],
        "chow, chow chow": [false, nil],
        "keeshond": [false, nil],
        "Brabancon griffon": [false, nil],
        "Pembroke, Pembroke Welsh corgi": [false, nil],
        "Cardigan, Cardigan Welsh corgi": [false, nil],
        "toy poodle": [false, nil],
        "miniature poodle": [false, nil],
        "standard poodle": [false, nil],
        "Mexican hairless": [false, nil],
        "timber wolf, grey wolf, gray wolf, Canis lupus": [false, nil],
        "white wolf, Arctic wolf, Canis lupus tundrarum": [false, nil],
        "red wolf, maned wolf, Canis rufus, Canis niger": [false, nil],
        "coyote, prairie wolf, brush wolf, Canis latrans": [false, nil],
        "dingo, warrigal, warragal, Canis dingo": [false, nil],
        "dhole, Cuon alpinus": [false, nil],
        "African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus": [false, nil],
        "hyena, hyaena": [false, nil],
        "red fox, Vulpes vulpes": [false, nil],
        "kit fox, Vulpes macrotis": [false, nil],
        "Arctic fox, white fox, Alopex lagopus": [false, nil],
        "grey fox, gray fox, Urocyon cinereoargenteus": [false, nil],
        "tabby, tabby cat": [false, nil],
        "tiger cat": [false, nil],
        "Persian cat": [false, nil],
        "Siamese cat, Siamese": [false, nil],
        "Egyptian cat": [false, nil],
        "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor": [false, nil],
        "lynx, catamount": [false, nil],
        "leopard, Panthera pardus": [false, nil],
        "snow leopard, ounce, Panthera uncia": [false, nil],
        "jaguar, panther, Panthera onca, Felis onca": [false, nil],
        "lion, king of beasts, Panthera leo": [false, nil],
        "tiger, Panthera tigris": [false, nil],
        "cheetah, chetah, Acinonyx jubatus": [false, nil],
        "brown bear, bruin, Ursus arctos": [false, nil],
        "American black bear, black bear, Ursus americanus, Euarctos americanus": [false, nil],
        "ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus": [false, nil],
        "sloth bear, Melursus ursinus, Ursus ursinus": [false, nil],
        "mongoose": [false, nil],
        "meerkat, mierkat": [false, nil],
        "tiger beetle": [false, nil],
        "ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle": [false, nil],
        "ground beetle, carabid beetle": [false, nil],
        "long-horned beetle, longicorn, longicorn beetle": [false, nil],
        "leaf beetle, chrysomelid": [false, nil],
        "dung beetle": [false, nil],
        "rhinoceros beetle": [false, nil],
        "weevil": [false, nil],
        "fly": [false, nil],
        "bee": [false, nil],
        "ant, emmet, pismire": [false, nil],
        "grasshopper, hopper": [false, nil],
        "cricket": [false, nil],
        "walking stick, walkingstick, stick insect": [false, nil],
        "cockroach, roach": [false, nil],
        "mantis, mantid": [false, nil],
        "cicada, cicala": [false, nil],
        "leafhopper": [false, nil],
        "lacewing, lacewing fly": [false, nil],
        "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk": [false, nil],
        "damselfly": [false, nil],
        "admiral": [false, nil],
        "ringlet, ringlet butterfly": [false, nil],
        "monarch, monarch butterfly, milkweed butterfly, Danaus plexippus": [false, nil],
        "cabbage butterfly": [false, nil],
        "sulphur butterfly, sulfur butterfly": [false, nil],
        "lycaenid, lycaenid butterfly": [false, nil],
        "starfish, sea star": [false, nil],
        "sea urchin": [false, nil],
        "sea cucumber, holothurian": [false, nil],
        "wood rabbit, cottontail, cottontail rabbit": [false, nil],
        "hare": [false, nil],
        "Angora, Angora rabbit": [false, nil],
        "hamster": [false, nil],
        "porcupine, hedgehog": [false, nil],
        "fox squirrel, eastern fox squirrel, Sciurus niger": [false, nil],
        "marmot": [false, nil],
        "beaver": [false, nil],
        "guinea pig, Cavia cobaya": [false, nil],
        "sorrel": [false, nil],
        "zebra": [false, nil],
        "hog, pig, grunter, squealer, Sus scrofa": [false, nil],
        "wild boar, boar, Sus scrofa": [false, nil],
        "warthog": [false, nil],
        "hippopotamus, hippo, river horse, Hippopotamus amphibius": [false, nil],
        "ox": [false, nil],
        "water buffalo, water ox, Asiatic buffalo, Bubalus bubalis": [false, nil],
        "bison": [false, nil],
        "ram, tup": [false, nil],
        "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis": [false, nil],
        "ibex, Capra ibex": [false, nil],
        "hartebeest": [false, nil],
        "impala, Aepyceros melampus": [false, nil],
        "gazelle": [false, nil],
        "Arabian camel, dromedary, Camelus dromedarius": [false, nil],
        "llama": [false, nil],
        "weasel": [false, nil],
        "mink": [false, nil],
        "polecat, fitch, foulmart, foumart, Mustela putorius": [false, nil],
        "black-footed ferret, ferret, Mustela nigripes": [false, nil],
        "otter": [false, nil],
        "skunk, polecat, wood pussy": [false, nil],
        "badger": [false, nil],
        "armadillo": [false, nil],
        "three-toed sloth, ai, Bradypus tridactylus": [false, nil],
        "orangutan, orang, orangutang, Pongo pygmaeus": [false, nil],
        "gorilla, Gorilla gorilla": [false, nil],
        "chimpanzee, chimp, Pan troglodytes": [false, nil],
        "gibbon, Hylobates lar": [false, nil],
        "siamang, Hylobates syndactylus, Symphalangus syndactylus": [false, nil],
        "guenon, guenon monkey": [false, nil],
        "patas, hussar monkey, Erythrocebus patas": [false, nil],
        "baboon": [false, nil],
        "macaque": [false, nil],
        "langur": [false, nil],
        "colobus, colobus monkey": [false, nil],
        "proboscis monkey, Nasalis larvatus": [false, nil],
        "marmoset": [false, nil],
        "capuchin, ringtail, Cebus capucinus": [false, nil],
        "howler monkey, howler": [false, nil],
        "titi, titi monkey": [false, nil],
        "spider monkey, Ateles geoffroyi": [false, nil],
        "squirrel monkey, Saimiri sciureus": [false, nil],
        "Madagascar cat, ring-tailed lemur, Lemur catta": [false, nil],
        "indri, indris, Indri indri, Indri brevicaudatus": [false, nil],
        "Indian elephant, Elephas maximus": [false, nil],
        "African elephant, Loxodonta africana": [false, nil],
        "lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens": [false, nil],
        "giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca": [false, nil],
        "barracouta, snoek": [false, nil],
        "eel": [false, nil],
        "coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch": [false, nil],
        "rock beauty, Holocanthus tricolor": [false, nil],
        "anemone fish": [false, nil],
        "sturgeon": [false, nil],
        "gar, garfish, garpike, billfish, Lepisosteus osseus": [false, nil],
        "lionfish": [false, nil],
        "puffer, pufferfish, blowfish, globefish": [false, nil],
        "abacus": [false, nil],
        "abaya": [false, nil],
        "academic gown, academic robe, judge's robe": [true, "https://interior.tn/diy/recycling-an-old-bathrobe-8-creative-ideas/"],
        "accordion, piano accordion, squeeze box": [false, nil],
        "acoustic guitar": [true, "https://musicsorbonline.com/5-creative-was-to-recycle-your-broken-guitar/"],
        "aircraft carrier, carrier, flattop, attack aircraft carrier": [false, nil],
        "airliner": [false, nil],
        "airship, dirigible": [false, nil],
        "altar": [false, nil],
        "ambulance": [false, nil],
        "amphibian, amphibious vehicle": [false, nil],
        "analog clock": [true, "https://homealarmclocks.com/how-to-recycle-or-dispose-of-old-clocks/"],
        "apiary, bee house": [false, nil],
        "apron": [false, nil],
        "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin": [true, "https://trashcansunlimited.com/blog/how-to-dispose-of-old-garbage-cans/"],
        "assault rifle, assault gun": [false, nil],
        "backpack, back pack, knapsack, packsack, rucksack, haversack": [true, "https://www.conserve-energy-future.com/can-you-recycle-backpacks.php"],
        "bakery, bakeshop, bakehouse": [false, nil],
        "balance beam, beam": [false, nil],
        "balloon": [false, nil],
        "ballpoint, ballpoint pen, ballpen, Biro": [true, "https://recyclenation.com/2015/10/how-to-recycle-pens"],
        "Band Aid": [true, nil],
        "banjo": [false, nil],
        "bannister, banister, balustrade, balusters, handrail": [false, nil],
        "barbell": [false, nil],
        "barber chair": [false, nil],
        "barbershop": [false, nil],
        "barn": [false, nil],
        "barometer": [false, nil],
        "barrel, cask": [true, nil],
        "barrow, garden cart, lawn cart, wheelbarrow": [false, nil],
        "baseball": [true, nil],
        "basketball": [true, nil],
        "bassinet": [false, nil],
        "bassoon": [false, nil],
        "bathing cap, swimming cap": [false, nil],
        "bath towel": [true, nil],
        "bathtub, bathing tub, bath, tub": [false, nil],
        "beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon": [true, "https://www.thefrugalgirl.com/how-to-recycle-a-wagon-and-give-away-not-perfect-t-shirts/"],
        "beacon, lighthouse, beacon light, pharos": [false, nil],
        "beaker": [false, nil],
        "bearskin, busby, shako": [false, nil],
        "beer bottle": [true, nil],
        "beer glass": [true, nil],
        "bell cote, bell cot": [false, nil],
        "bib": [false, nil],
        "bicycle-built-for-two, tandem bicycle, tandem": [false, "https://www.1800gotjunk.com/us_en/blog/environment/how-recycle-bicycle"],
        "bikini, two-piece": [false, nil],
        "binder, ring-binder": [true, "https://www.scarce.org/recycling-faq-binders/"],
        "binoculars, field glasses, opera glasses": [true, "https://www.audubon.org/news/what-do-your-old-binoculars"],
        "birdhouse": [false, nil],
        "boathouse": [false, nil],
        "bobsled, bobsleigh, bob": [false, nil],
        "bolo tie, bolo, bola tie, bola": [false, nil],
        "bonnet, poke bonnet": [false, nil],
        "bookcase": [false, nil],
        "bookshop, bookstore, bookstall": [false, nil],
        "bottlecap": [true, nil],
        "bow": [false, nil],
        "bow tie, bow-tie, bowtie": [false, nil],
        "brass, memorial tablet, plaque": [true, nil],
        "brassiere, bra, bandeau": [true, "https://earth911.com/how-to-recycle/recycling-mystery-underwear/#:~:text=Bra%20Recycling%20and%20Donation&text=The%20Bra%20Recyclers%20will%20recycle,Girls%2C%20or%20The%20Undies%20Project."],
        "breakwater, groin, groyne, mole, bulwark, seawall, jetty": [false, nil],
        "breastplate, aegis, egis": [false, nil],
        "broom": [false, nil],
        "bucket, pail": [true, nil],
        "buckle": [false, nil],
        "bulletproof vest": [false, nil],
        "bullet train, bullet": [false, nil],
        "butcher shop, meat market": [false, nil],
        "cab, hack, taxi, taxicab": [false, nil],
        "caldron, cauldron": [false, nil],
        "candle, taper, wax light": [false, nil],
        "cannon": [false, nil],
        "canoe": [true, "https://goloadup.com/what-we-take/sports-equipment/canoe-removal/"],
        "can opener, tin opener": [true, "https://www.goingzerowaste.com/blog/how-to-recycle-correctly/#:~:text=Steel%20can%20lids%20are%20recyclable,is%20still%20sorted%20by%20hand."],
        "cardigan": [false, nil],
        "car mirror": [false, nil],
        "carousel, carrousel, merry-go-round, roundabout, whirligig": [false, nil],
        "carpenter's kit, tool kit": [false, nil],
        "carton": [false, nil],
        "car wheel": [true, "https://www.wheelsforwishes.org/news/how-to-dispose-of-tires-and-rims/"],
        "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM": [false, nil],
        "cassette": [false, nil],
        "cassette player": [false, nil],
        "castle": [false, nil],
        "catamaran": [false, nil],
        "CD player": [false, nil],
        "cello, violoncello": [false, nil],
        "cellular telephone, cellular phone, cellphone, cell, mobile phone": [true, "https://www.apple.com/shop/trade-in"],
        "chain": [false, nil],
        "chainlink fence": [false, nil],
        "chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour": [false, nil],
        "chain saw, chainsaw": [true, "https://naparecycling.com/guide/chainsaws/"],
        "chest": [false, nil],
        "chiffonier, commode": [false, nil],
        "chime, bell, gong": [false, nil],
        "china cabinet, china closet": [false, nil],
        "Christmas stocking": [false, nil],
        "church, church building": [false, nil],
        "cinema, movie theater, movie theatre, movie house, picture palace": [false, nil],
        "cleaver, meat cleaver, chopper": [false, nil],
        "cliff dwelling": [false, nil],
        "cloak": [false, nil],
        "clog, geta, patten, sabot": [false, nil],
        "cocktail shaker": [false, nil],
        "coffee mug": [true, "https://www.wikihow.com/Recycle-Old-Coffee-Mugs#:~:text=Thrift%20stores%20that%20sell%20housewares,ready%20to%20be%20recycled%20again.&text=Ask%20your%20recycling%20program%20if%20they%20accept%20ceramic."],
        "coffeepot": [false, nil],
        "coil, spiral, volute, whorl, helix": [true, nil],
        "combination lock": [true, "https://findanyanswer.com/can-you-recycle-master-locks"],
        "computer keyboard, keypad": [true, nil],
        "confectionery, confectionary, candy store": [false, nil],
        "container ship, containership, container vessel": [false, nil],
        "convertible": [false, nil],
        "corkscrew, bottle screw": [false, nil],
        "cornet, horn, trumpet, trump": [false, nil],
        "cowboy boot": [false, nil],
        "cowboy hat, ten-gallon hat": [false, nil],
        "cradle": [false, nil],
        "crane": [false, nil],
        "crash helmet": [true, "https://helmets.org/recycle.htm#:~:text=Most%20local%20recycling%20programs%20don,and%20buckle%20in%20the%20trash."],
        "crate": [false, nil],
        "crib, cot": [true, "https://goloadup.com/what-we-take/baby-gear/crib-disposal/"],
        "Crock Pot": [false, nil],
        "croquet ball": [false, nil],
        "crutch": [true, nil],
        "cuirass": [false, nil],
        "dam, dike, dyke": [false, nil],
        "desk": [true, "https://www.greenhomeguide.com/know-how/article/5-ways-to-recycle-your-old-furniture"],
        "desktop computer": [true, "https://www.apple.com/shop/trade-in"],
        "dial telephone, dial phone": [true, "https://www.hunker.com/12001158/how-to-recycle-landline-phones#:~:text=Earth911.org%20(see%20Resources%20below,material%20that%20can%20be%20recycled."],
        "diaper, nappy, napkin": [false, nil],
        "digital clock": [true, "https://earth911.com/recycling-guide/how-to-recycle-small-electronics/"],
        "digital watch": [true, "https://earth911.com/recycling-guide/how-to-recycle-small-electronics/"],
        "dining table, board": [false, nil],
        "dishrag, dishcloth": [false, nil],
        "dishwasher, dish washer, dishwashing machine": [true, "https://www.dumpsters.com/disposal-guides/getting-rid-of-old-appliances#:~:text=If%20you%20can't%20find,a%20buy%2Dback%20recycling%20program."],
        "disk brake, disc brake": [false, nil],
        "dock, dockage, docking facility": [false, nil],
        "dogsled, dog sled, dog sleigh": [false, nil],
        "dome": [false, nil],
        "doormat, welcome mat": [false, nil],
        "drilling platform, offshore rig": [false, nil],
        "drum, membranophone, tympan": [true, nil],
        "drumstick": [false, nil],
        "dumbbell": [false, nil],
        "Dutch oven": [false, nil],
        "electric fan, blower": [true, "https://www.hunterfan.com/blogs/hunter-blog/how-to-recycle-a-ceiling-fan#:~:text=Organizations%20like%20The%20Salvation%20Army,it%20up%20from%20your%20home."],
        "electric guitar": [true, "https://musicsorbonline.com/5-creative-was-to-recycle-your-broken-guitar/"],
        "electric locomotive": [false, nil],
        "entertainment center": [false, nil],
        "envelope": [true, nil],
        "espresso maker": [false, nil],
        "face powder": [false, nil],
        "feather boa, boa": [false, nil],
        "file, file cabinet, filing cabinet": [true, "https://recyclenation.com/2012/03/recycle-file-cabinets/#:~:text=If%20that%20still%20doesn't,it%20down%20for%20scrap%20metal."],
        "fireboat": [false, nil],
        "fire engine, fire truck": [false, nil],
        "fire screen, fireguard": [false, nil],
        "flagpole, flagstaff": [false, nil],
        "flute, transverse flute": [false, nil],
        "folding chair": [false, nil],
        "football helmet": [true, "https://helmets.org/recycle.htm#:~:text=Most%20local%20recycling%20programs%20don,and%20buckle%20in%20the%20trash."],
        "forklift": [false, nil],
        "fountain": [false, nil],
        "fountain pen": [true, "https://recyclenation.com/2015/10/how-to-recycle-pens/#:~:text=The%20easiest%20way%20to%20recycle,highlighters%2C%20markers%20and%20mechanical%20pencils."],
        "four-poster": [false, nil],
        "freight car": [false, nil],
        "French horn, horn": [false, nil],
        "frying pan, frypan, skillet": [false, nil],
        "fur coat": [false, nil],
        "garbage truck, dustcart": [false, nil],
        "gasmask, respirator, gas helmet": [false, nil],
        "gas pump, gasoline pump, petrol pump, island dispenser": [false, nil],
        "goblet": [false, nil],
        "go-kart": [false, nil],
        "golf ball": [false, nil],
        "golfcart, golf cart": [false, nil],
        "gondola": [false, nil],
        "gong, tam-tam": [false, nil],
        "gown": [false, nil],
        "grand piano, grand": [false, nil],
        "greenhouse, nursery, glasshouse": [false, nil],
        "grille, radiator grille": [false, nil],
        "grocery store, grocery, food market, market": [false, nil],
        "guillotine": [false, nil],
        "hair slide": [false, nil],
        "hair spray": [false, nil],
        "half track": [false, nil],
        "hammer": [true, "https://www.familyhandyman.com/article/how-to-recycle-old-tools/"],
        "hamper": [false, nil],
        "hand blower, blow dryer, blow drier, hair dryer, hair drier": [false, nil],
        "hand-held computer, hand-held microcomputer": [true, nil],
        "handkerchief, hankie, hanky, hankey": [false, "https://startsat60.com/media/lifestyle/8-ways-to-recycle-your-old-handkerchiefs/amp"],
        "hard disc, hard disk, fixed disk": [false, nil],
        "harmonica, mouth organ, harp, mouth harp": [false, nil],
        "harp": [false, nil],
        "harvester, reaper": [false, nil],
        "hatchet": [false, nil],
        "holster": [false, nil],
        "home theater, home theatre": [false, nil],
        "honeycomb": [false, nil],
        "hook, claw": [false, nil],
        "hoopskirt, crinoline": [false, nil],
        "horizontal bar, high bar": [false, nil],
        "horse cart, horse-cart": [false, nil],
        "hourglass": [false, nil],
        "iPod": [true, "https://www.apple.com/shop/trade-in"],
        "iron, smoothing iron": [false, nil],
        "jack-o'-lantern": [false, nil],
        "jean, blue jean, denim": [true, nil],
        "jeep, landrover": [false, nil],
        "jersey, T-shirt, tee shirt": [false, nil],
        "jigsaw puzzle": [true, nil],
        "jinrikisha, ricksha, rickshaw": [false, nil],
        "joystick": [false, nil],
        "kimono": [false, nil],
        "knee pad": [false, nil],
        "knot": [false, nil],
        "lab coat, laboratory coat": [true, "https://www.unmc.edu/news.cfm?match=16502"],
        "ladle": [false, nil],
        "lampshade, lamp shade": [false, nil],
        "laptop, laptop computer": [true, "https://www.apple.com/shop/trade-in"],
        "lawn mower, mower": [false, nil],
        "lens cap, lens cover": [false, nil],
        "letter opener, paper knife, paperknife": [true, nil],
        "library": [false, nil],
        "lifeboat": [false, nil],
        "lighter, light, igniter, ignitor": [false, nil],
        "limousine, limo": [false, nil],
        "liner, ocean liner": [false, nil],
        "lipstick, lip rouge": [false, nil],
        "Loafer": [false, nil],
        "lotion": [false, nil],
        "loudspeaker, speaker, speaker unit, loudspeaker system, speaker system": [false, nil],
        "loupe, jeweler's loupe": [false, nil],
        "lumbermill, sawmill": [false, nil],
        "magnetic compass": [false, nil],
        "mailbag, postbag": [false, nil],
        "mailbox, letter box": [false, nil],
        "maillot": [false, nil],
        "maillot, tank suit": [false, nil],
        "manhole cover": [false, nil],
        "maraca": [false, nil],
        "marimba, xylophone": [false, nil],
        "mask": [false, nil],
        "matchstick": [false, nil],
        "maypole": [false, nil],
        "maze, labyrinth": [false, nil],
        "measuring cup": [true, nil],
        "medicine chest, medicine cabinet": [false, nil],
        "megalith, megalithic structure": [false, nil],
        "microphone, mike": [false, nil],
        "microwave, microwave oven": [false, nil],
        "military uniform": [false, nil],
        "milk can": [false, nil],
        "minibus": [false, nil],
        "miniskirt, mini": [true, "https://www.rd.com/article/clothes-recycling/"],
        "minivan": [false, nil],
        "missile": [false, nil],
        "mitten": [false, nil],
        "mixing bowl": [false, nil],
        "mobile home, manufactured home": [false, nil],
        "Model T": [false, nil],
        "modem": [false, nil],
        "monastery": [false, nil],
        "monitor": [false, nil],
        "moped": [false, nil],
        "mortar": [false, nil],
        "mortarboard": [false, nil],
        "mosque": [false, nil],
        "mosquito net": [false, nil],
        "motor scooter, scooter": [false, nil],
        "mountain bike, all-terrain bike, off-roader": [false, nil],
        "mountain tent": [false, nil],
        "mouse, computer mouse": [true, nil],
        "mousetrap": [false, nil],
        "moving van": [false, nil],
        "muzzle": [false, nil],
        "nail": [false, nil],
        "neck brace": [false, nil],
        "necklace": [false, nil],
        "nipple": [false, nil],
        "notebook, notebook computer": [true, "https://www.apple.com/shop/trade-in"],
        "obelisk": [false, nil],
        "oboe, hautboy, hautbois": [false, nil],
        "ocarina, sweet potato": [false, nil],
        "odometer, hodometer, mileometer, milometer": [false, nil],
        "oil filter": [false, nil],
        "organ, pipe organ": [false, nil],
        "oscilloscope, scope, cathode-ray oscilloscope, CRO": [false, nil],
        "overskirt": [false, nil],
        "oxcart": [false, nil],
        "oxygen mask": [false, nil],
        "packet": [false, nil],
        "paddle, boat paddle": [false, nil],
        "paddlewheel, paddle wheel": [false, nil],
        "padlock": [false, nil],
        "paintbrush": [false, nil],
        "pajama, pyjama, pj's, jammies": [true, "https://www.rd.com/article/clothes-recycling/"],
        "palace": [false, nil],
        "panpipe, pandean pipe, syrinx": [false, nil],
        "paper towel": [true, nil],
        "parachute, chute": [false, nil],
        "parallel bars, bars": [false, nil],
        "park bench": [false, nil],
        "parking meter": [false, nil],
        "passenger car, coach, carriage": [false, nil],
        "patio, terrace": [false, nil],
        "pay-phone, pay-station": [false, nil],
        "pedestal, plinth, footstall": [false, nil],
        "pencil box, pencil case": [false, nil],
        "pencil sharpener": [false, nil],
        "perfume, essence": [false, nil],
        "Petri dish": [false, nil],
        "photocopier": [false, nil],
        "pick, plectrum, plectron": [false, nil],
        "pickelhaube": [false, nil],
        "picket fence, paling": [false, nil],
        "pickup, pickup truck": [false, nil],
        "pier": [false, nil],
        "piggy bank, penny bank": [false, nil],
        "pill bottle": [false, nil],
        "pillow": [false, nil],
        "ping-pong ball": [false, nil],
        "pinwheel": [false, nil],
        "pirate, pirate ship": [false, nil],
        "pitcher, ewer": [false, nil],
        "plane, carpenter's plane, woodworking plane": [false, nil],
        "planetarium": [false, nil],
        "plastic bag": [true, nil],
        "plate rack": [false, nil],
        "plow, plough": [false, nil],
        "plunger, plumber's helper": [false, nil],
        "Polaroid camera, Polaroid Land camera": [false, nil],
        "pole": [false, nil],
        "police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria": [false, nil],
        "poncho": [false, nil],
        "pool table, billiard table, snooker table": [false, nil],
        "pop bottle, soda bottle": [false, nil],
        "pot, flowerpot": [false, nil],
        "potter's wheel": [false, nil],
        "power drill": [false, nil],
        "prayer rug, prayer mat": [false, nil],
        "printer": [false, nil],
        "prison, prison house": [false, nil],
        "projectile, missile": [false, nil],
        "projector": [false, nil],
        "puck, hockey puck": [false, nil],
        "punching bag, punch bag, punching ball, punchball": [false, nil],
        "purse": [false, nil],
        "quill, quill pen": [false, nil],
        "quilt, comforter, comfort, puff": [false, nil],
        "racer, race car, racing car": [false, nil],
        "racket, racquet": [false, nil],
        "radiator": [false, nil],
        "radio, wireless": [true, "https://junkrelief.com/2019/04/27/e-cycling-chicago/"],
        "radio telescope, radio reflector": [false, nil],
        "rain barrel": [false, nil],
        "recreational vehicle, RV, R.V.": [false, nil],
        "reel": [false, nil],
        "reflex camera": [false, nil],
        "refrigerator, icebox": [false, nil],
        "remote control, remote": [true, "https://electronics.howstuffworks.com/how-to-recycle-remote-controls.htm"],
        "restaurant, eating house, eating place, eatery": [false, nil],
        "revolver, six-gun, six-shooter": [false, nil],
        "rifle": [false, nil],
        "rocking chair, rocker": [false, nil],
        "rotisserie": [false, nil],
        "rubber eraser, rubber, pencil eraser": [false, nil],
        "rugby ball": [false, nil],
        "rule, ruler": [false, nil],
        "running shoe": [false, "https://brightly.eco/how-to-recycle-shoes/"],
        "safe": [false, nil],
        "safety pin": [true, nil],
        "saltshaker, salt shaker": [false, nil],
        "sandal": [false, nil],
        "sarong": [false, nil],
        "sax, saxophone": [false, nil],
        "scabbard": [false, nil],
        "scale, weighing machine": [false, nil],
        "school bus": [false, nil],
        "schooner": [false, nil],
        "scoreboard": [false, nil],
        "screen, CRT screen": [false, nil],
        "screw": [true, nil],
        "screwdriver": [false, nil],
        "seat belt, seatbelt": [false, nil],
        "sewing machine": [false, nil],
        "shield, buckler": [false, nil],
        "shoe shop, shoe-shop, shoe store": [false, nil],
        "shoji": [false, nil],
        "shopping basket": [false, nil],
        "shopping cart": [false, nil],
        "shovel": [true, "https://www.mansfieldct.gov/1551/How-Do-I-Get-Rid-of-This#!rc-cpage=45567"],
        "shower cap": [true, "https://toughnickel.com/frugal-living/Shower-Caps-Disposable-and-Reusable-20-ways"],
        "shower curtain": [false, nil],
        "ski": [true, "https://www.backcountry.com/explore/what-to-do-with-your-old-skis"],
        "ski mask": [false, nil],
        "sleeping bag": [false, nil],
        "slide rule, slipstick": [false, nil],
        "sliding door": [false, nil],
        "slot, one-armed bandit": [false, nil],
        "snorkel": [false, nil],
        "snowmobile": [false, nil],
        "snowplow, snowplough": [false, nil],
        "soap dispenser": [true, nil],
        "soccer ball": [false, nil],
        "sock": [true, nil],
        "solar dish, solar collector, solar furnace": [false, nil],
        "sombrero": [false, nil],
        "soup bowl": [false, nil],
        "space bar": [false, nil],
        "space heater": [false, nil],
        "space shuttle": [false, nil],
        "spatula": [false, nil],
        "speedboat": [false, nil],
        "spider web, spider's web": [false, nil],
        "spindle": [false, nil],
        "sports car, sport car": [false, nil],
        "spotlight, spot": [false, nil],
        "stage": [false, nil],
        "steam locomotive": [false, nil],
        "steel arch bridge": [false, nil],
        "steel drum": [false, nil],
        "stethoscope": [false, nil],
        "stole": [false, nil],
        "stone wall": [false, nil],
        "stopwatch, stop watch": [false, nil],
        "stove": [false, nil],
        "strainer": [false, nil],
        "streetcar, tram, tramcar, trolley, trolley car": [false, nil],
        "stretcher": [false, nil],
        "studio couch, day bed": [false, nil],
        "stupa, tope": [false, nil],
        "submarine, pigboat, sub, U-boat": [false, nil],
        "suit, suit of clothes": [false, nil],
        "sundial": [false, nil],
        "sunglass": [false, nil],
        "sunglasses, dark glasses, shades": [true, nil],
        "sunscreen, sunblock, sun blocker": [true, nil],
        "suspension bridge": [false, nil],
        "swab, swob, mop": [false, nil],
        "sweatshirt": [false, nil],
        "swimming trunks, bathing trunks": [false, nil],
        "swing": [false, nil],
        "switch, electric switch, electrical switch": [false, nil],
        "syringe": [false, nil],
        "table lamp": [false, nil],
        "tank, army tank, armored combat vehicle, armoured combat vehicle": [false, nil],
        "tape player": [false, nil],
        "teapot": [false, nil],
        "teddy, teddy bear": [false, nil],
        "television, television system": [false, nil],
        "tennis ball": [false, nil],
        "thatch, thatched roof": [false, nil],
        "theater curtain, theatre curtain": [false, nil],
        "thimble": [false, nil],
        "thresher, thrasher, threshing machine": [false, nil],
        "throne": [false, nil],
        "tile roof": [false, nil],
        "toaster": [false, nil],
        "tobacco shop, tobacconist shop, tobacconist": [false, nil],
        "toilet seat": [false, nil],
        "torch": [false, nil],
        "totem pole": [false, nil],
        "tow truck, tow car, wrecker": [false, nil],
        "toyshop": [false, nil],
        "tractor": [false, nil],
        "trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi": [false, nil],
        "tray": [false, nil],
        "trench coat": [false, nil],
        "tricycle, trike, velocipede": [false, nil],
        "trimaran": [false, nil],
        "tripod": [false, nil],
        "triumphal arch": [false, nil],
        "trolleybus, trolley coach, trackless trolley": [false, nil],
        "trombone": [false, nil],
        "tub, vat": [false, nil],
        "turnstile": [false, nil],
        "typewriter keyboard": [false, nil],
        "umbrella": [true, nil],
        "unicycle, monocycle": [false, nil],
        "upright, upright piano": [false, nil],
        "vacuum, vacuum cleaner": [false, nil],
        "vase": [false, nil],
        "vault": [false, nil],
        "velvet": [false, nil],
        "vending machine": [false, nil],
        "vestment": [false, nil],
        "viaduct": [false, nil],
        "violin, fiddle": [true, "https://www.grushecky.com/how-to-recycle-a-violin/"],
        "volleyball": [false, nil],
        "waffle iron": [false, nil],
        "wall clock": [false, nil],
        "wallet, billfold, notecase, pocketbook": [false, nil],
        "wardrobe, closet, press": [false, nil],
        "warplane, military plane": [false, nil],
        "washbasin, handbasin, washbowl, lavabo, wash-hand basin": [false, nil],
        "washer, automatic washer, washing machine": [true, "https://greencitizen.com/dispose-of-a-washer-and-dryer/"],
        "water bottle": [true, nil],
        "water jug": [true, nil],
        "water tower": [false, nil],
        "whiskey jug": [true, nil],
        "whistle": [true, "https://www.pinterest.es/pin/366621225897846504/"],
        "wig": [true, "https://thewigstation.com/recycling/"],
        "window screen": [true, "https://www.metroscreenworks.com/blog/10-ways-to-recycle-old-window-screens/"],
        "window shade": [true, "https://shuttermasters.com/how-to-recycle-blinds/"],
        "Windsor tie": [true, nil],
        "wine bottle": [true, nil],
        "wing": [false, nil],
        "wok": [true, "https://earth911.com/home-garden/how-to-recycle-your-old-cookware/"],
        "wooden spoon": [true, nil],
        "wool, woolen, woollen": [true, "https://iwto.org/sustainability/recycled-wool/"],
        "worm fence, snake fence, snake-rail fence, Virginia fence": [true, "https://fencesupplyonline.com/blog/can-you-recycle-your-old-fence/"],
        "wreck": [false, nil],
        "yawl": [true, "https://newdayreuse.org/how-to-get-rid-of-an-old-boat-5-easy-ways/"],
        "yurt": [true, "https://www.yurtforum.com/forums/simplicity-f18/woolcool-recycle-1592.html"],
        "web site, website, internet site, site": [false, nil],
        "comic book": [true, nil],
        "crossword puzzle, crossword": [true, nil],
        "street sign": [true, "https://iscrapapp.com/blog/scrapping-aluminum-street-signs/"],
        "traffic light, traffic signal, stoplight": [true, "https://green.thefuntimesguide.com/old-traffic-light/"],
        "book jacket, dust cover, dust jacket, dust wrapper": [true, nil],
        "menu": [true, nil],
        "plate": [true, nil],
        "guacamole": [true, "https://www.youtube.com/watch?v=uJY2A-HaQRY"],
        "consomme": [true, "https://www.rcbc.ca/resources/faqs/beverage8"],
        "hot pot, hotpot": [true, "https://greencitizen.com/appliance-recycling/"],
        "trifle": [true, "https://www.youtube.com/watch?v=_AkxIJ60fYs"],
        "ice cream, icecream": [true, "https://www.conserve-energy-future.com/are-ice-cream-cartons-recyclable.php"],
        "ice lolly, lolly, lollipop, popsicle": [true, "https://www.sprucegrove.org/services/garbage-organics-recycling/organics/#!rc-cpage=347825"],
        "French loaf": [true, "https://www.businessinsider.com/crumbler-bread-crumbs-france-food-waste-2021-3"],
        "bagel, beigel": [false, nil],
        "pretzel": [false, nil],
        "cheeseburger": [false, nil],
        "hotdog, hot dog, red hot": [false, nil],
        "mashed potato": [false, nil],
        "head cabbage": [false, nil],
        "broccoli": [false, nil],
        "cauliflower": [false, nil],
        "zucchini, courgette": [false, nil],
        "spaghetti squash": [false, nil],
        "acorn squash": [false, nil],
        "butternut squash": [false, nil],
        "cucumber, cuke": [false, nil],
        "artichoke, globe artichoke": [false, nil],
        "bell pepper": [false, nil],
        "cardoon": [false, nil],
        "mushroom": [false, nil],
        "Granny Smith": [false, nil],
        "strawberry": [false, nil],
        "orange": [false, nil],
        "lemon": [false, nil],
        "fig": [false, nil],
        "pineapple, ananas": [false, nil],
        "banana": [false, nil],
        "jackfruit, jak, jack": [false, nil],
        "custard apple": [false, nil],
        "pomegranate": [false, nil],
        "hay": [false, nil],
        "carbonara": [false, nil],
        "chocolate sauce, chocolate syrup": [false, nil],
        "dough": [false, nil],
        "meat loaf, meatloaf": [false, nil],
        "pizza, pizza pie": [false, nil],
        "potpie": [false, nil],
        "burrito": [false, nil],
        "red wine": [false, nil],
        "espresso": [false, nil],
        "cup": [false, nil],
        "eggnog": [false, nil],
        "alp": [false, nil],
        "bubble": [false, nil],
        "cliff, drop, drop-off": [false, nil],
        "coral reef": [false, nil],
        "geyser": [false, nil],
        "lakeside, lakeshore": [false, nil],
        "promontory, headland, head, foreland": [false, nil],
        "sandbar, sand bar": [false, nil],
        "seashore, coast, seacoast, sea-coast": [false, nil],
        "valley, vale": [false, nil],
        "volcano": [false, nil],
        "ballplayer, baseball player": [false, nil],
        "groom, bridegroom": [false, nil],
        "scuba diver": [false, nil],
        "rapeseed": [false, nil],
        "daisy": [false, nil],
        "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum": [false, nil],
        "corn": [false, nil],
        "acorn": [false, nil],
        "hip, rose hip, rosehip": [false, nil],
        "buckeye, horse chestnut, conker": [false, nil],
        "coral fungus": [false, nil],
        "agaric": [false, nil],
        "gyromitra": [false, nil],
        "stinkhorn, carrion fungus": [false, nil],
        "earthstar": [false, nil],
        "hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa": [false, nil],
        "bolete": [false, nil],
        "ear, spike, capitulum": [false, nil],
        "toilet tissue, toilet paper, bathroom tissue": [true, nil]
    ]
}
